### PR TITLE
decrypt.py python3 support

### PR DESCRIPTION
**Pull request by Atem18**
WIP

### CODE REVIEW

**Comment by Atem18** [comment]
@shijimasoft I have the following error:

```python
  File "/Users/atem/Repos/cia-unix/decrypt.py", line 390, in parseNCCH
    tmp = tmp[:399] + chr(ord(tmp[399]) & 2 | 4) + tmp[400:]
TypeError: ord() expected string of length 1, but int found
```
tmp[399] is equal to 0. What should be the correct value ?

Thanks a lot in advance.

**Comment by shijimasoft** [comment]
It depends on the partition you're going to read (different from each rom)
But the error seems to be a casting exception-

To be sure, try adding log messages in the python2 script

**Comment by Atem18** [comment]
@shijimasoft Now, I can generate a file but it crash when opening it with Citra :/

**Comment by shijimasoft** [comment]
One step forward!
I recommend you the `unittest` library to compare results between *python2* and *python3* scripts 😄

**Comment by shijimasoft** [comment]
@Atem18, I will change some things in `cia-unix.cr` file to support python3

**Comment by shijimasoft** [comment]
Just created a new [experimental](https://github.com/shijimasoft/cia-unix/tree/experimental) branch with these new changes

**Comment by Atem18** [comment]
@shijimasoft Thanks a lot !

**Pull request merged**
